# Generated by Django 5.0.1 on 2024-02-03 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'managed': True, 'verbose_name': 'game', 'verbose_name_plural': 'games'},
        ),
        migrations.AlterModelTable(
            name='game',
            table='games',
        ),
    ]
